name : komi


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ master ]
      
env:
  API_ID: ${{secrets.API_ID}}
  API_HASH: ${{secrets.API_HASH}}
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  MONGO_URL: ${{secrets.MONGO_URL}}
  REDIS_URL: ${{secrets.REDIS_URL}}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
           
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.9.1
         with:
              access_token: ${{ github.token }}

       - name: cloning repo and install
         continue-on-error: true
         run: |
           git clone https://github.com/NksamaX/Komi-San komi && cd komi && pip3 install -r requirements.txt
           pwd
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
           pwd
           cd komi
           python3 -m nksama
